# Selectors
LOG_IN_BUTTON = 'new UiSelector().text("Log in")'
EMAIL_INPUT = 'new UiSelector().text("Email")'
PASSWORD_INPUT = 'new UiSelector().text("Password")'
CONFIRM_PASSWORD_INPUT = 'new UiSelector().text("Confirm password")'
NAME_INPUT = 'new UiSelector().text("Name")'
EMAIL_ALREADY_EXISTS_TOAST = 'new UiSelector().text("Email already exists")'
WRONG_EMAIL_OR_PASSWORD_TOAST = 'new UiSelector().text("wrong email or password")'
LOGIN_PAGE_VIEW_GROUP = 'new UiSelector().className("android.view.ViewGroup").instance(41)'
PASSWORD_VIEW_GROUP = 'new UiSelector().className("android.view.ViewGroup").instance(45)'
SIGNUP_VIEW_GROUP = 'new UiSelector().className("android.view.ViewGroup").instance(51)'
FINALIZE_SIGNUP_VIEW_GROUP = 'new UiSelector().className("android.view.ViewGroup").instance(46)'
BACK_BUTTON_PATH_VIEW = 'new UiSelector().className("com.horcrux.svg.PathView")'
FINALIZE_LOGIN_VIEW_GROUP = 'new UiSelector().className("android.view.ViewGroup").instance(50)'
